[auth]  # seção obrigatória

redirect_uri = "http://localhost:8501/oauth2callback"   # ou domínio de produção
client_id     = "179362054535-h1jnsf91d9ap9a1a4fju2687vkhsiepv.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"

# ASSINATURA DE COOKIE – STRING BEM LONGA
cookie_secret = "mvkQx6N01czH5oNj1k2x9DS6Hc-Km2Wi6EUPsG2JX0E="
